dist: bionic

sudo: true

git:
  depth: false

addons:
  hosts:
    - magento2.docker
    - magento2.test

services:
  - docker

language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

env:
  - TEST_SUITE=functional

stages:
  - static-unit
  - integration
  - test

jobs:
  include:
    - stage: static-unit
      script: ./tests/travis/static-unit.sh;
      env:
        - TEST_SUITE=static-unit
    - script: ./tests/travis/static-unit.sh;
      php: '7.2'
      env:
        - TEST_SUITE=static-unit
    - script: ./tests/travis/static-unit.sh;
      php: '7.3'
      env:
        - TEST_SUITE=static-unit
    - stage: integration
      script: ./vendor/bin/phpunit --configuration ./tests/integration;
      env:
        - TEST_SUITE=integration
    - script: ./vendor/bin/phpunit --configuration ./tests/integration;
      php: '7.2'
      env:
        - TEST_SUITE=integration
    - script: ./vendor/bin/phpunit --configuration ./tests/integration;
      php: '7.3'
      env:
        - TEST_SUITE=integration
    - stage: test
      script: if [ $TRAVIS_SECURE_ENV_VARS == "true" ]; then ./tests/travis/functional.sh; fi;
      dist: xenial
      env:
        - TEST_SUITE=functional
    - script: if [ $TRAVIS_SECURE_ENV_VARS == "true" ]; then ./tests/travis/functional.sh; fi;
      dist: xenial
      php: '7.2'
      env:
        - TEST_SUITE=functional
    - script: if [ $TRAVIS_SECURE_ENV_VARS == "true" ]; then ./tests/travis/functional.sh; fi;
      php: '7.3'
      env:
        - TEST_SUITE=functional

install: composer update

before_script:
  - sudo sysctl -w vm.max_map_count=262144
